# Generated by Django 6.0.2 on 2026-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], help_text='The allauth provider key (e.g. "google").', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Shown on the login button.', max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='When disabled, the login button is hidden regardless of credentials.')),
                ('client_id', models.CharField(blank=True, max_length=500)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Optional provider-specific JSON config passed to allauth.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Auth Provider',
                'verbose_name_plural': 'Social Auth Providers',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from social login (Google, Facebook, etc.).', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_provider',
            field=models.CharField(blank=True, help_text='Which social provider was used to create this account (e.g. "google").', max_length=50),
        ),
    ]
