# Generated by Django 6.0.2 on 2026-03-02 (modified to include data migration)
#
# Why this migration exists:
# Sensitive fields (OAuth secrets, guest PII) were stored as plain text.
# We now encrypt them at rest using AES-128 via Fernet (django-encrypted-model-fields).
#
# Data migration strategy:
# 1. Read existing plain text values via raw SQL (bypasses EncryptedField.from_db_value).
# 2. Encrypt each value using the same Fernet key that the ORM will use going forward.
# 3. Write back via raw SQL UPDATE.
# The AlterField operations that follow are schema-only (VARCHAR stays VARCHAR),
# so existing encrypted blobs remain valid after migration.

import encrypted_model_fields.fields
from django.db import migrations, connection
from django.conf import settings


def _encrypt_column(cursor, table, pk_col, column):
    """Read plain text from `column`, write back as Fernet tokens."""
    from cryptography.fernet import Fernet, InvalidToken

    key = settings.FIELD_ENCRYPTION_KEY
    if not key:
        return  # No key configured — skip (dev without encryption key)
    if isinstance(key, (list, tuple)):
        key = key[0]
    f = Fernet(key.encode() if isinstance(key, str) else key)

    cursor.execute(f"SELECT {pk_col}, {column} FROM {table} WHERE {column} != '' AND {column} IS NOT NULL")
    rows = cursor.fetchall()
    for row_id, value in rows:
        # Skip values that are already Fernet tokens (already encrypted)
        if value and value.startswith('gAAA'):
            continue
        try:
            encrypted = f.encrypt(value.encode('utf-8')).decode('utf-8')
            cursor.execute(
                f"UPDATE {table} SET {column} = %s WHERE {pk_col} = %s",
                [encrypted, row_id],
            )
        except Exception:
            # If encryption fails, clear the value rather than store bad data
            cursor.execute(f"UPDATE {table} SET {column} = '' WHERE {pk_col} = %s", [row_id])


def encrypt_existing_data(apps, schema_editor):
    """Encrypt any existing plain text values before AlterField takes effect."""
    with connection.cursor() as cursor:
        # SocialAuthProvider
        _encrypt_column(cursor, 'accounts_socialauthprovider', 'id', 'client_id')
        _encrypt_column(cursor, 'accounts_socialauthprovider', 'id', 'client_secret')
        # UserProfile PII
        _encrypt_column(cursor, 'accounts_userprofile', 'id', 'phone_whatsapp')
        _encrypt_column(cursor, 'accounts_userprofile', 'id', 'medical_conditions')
        _encrypt_column(cursor, 'accounts_userprofile', 'id', 'dietary_requirements')
        _encrypt_column(cursor, 'accounts_userprofile', 'id', 'personal_notes')
        # date_of_birth is a DATE column — convert to string first
        cursor.execute(
            "SELECT id, date_of_birth FROM accounts_userprofile "
            "WHERE date_of_birth IS NOT NULL"
        )
        rows = cursor.fetchall()
        if rows:
            from cryptography.fernet import Fernet
            key = settings.FIELD_ENCRYPTION_KEY
            if key:
                if isinstance(key, (list, tuple)):
                    key = key[0]
                f = Fernet(key.encode() if isinstance(key, str) else key)
                for row_id, dob in rows:
                    dob_str = str(dob)
                    if dob_str.startswith('gAAA'):
                        continue
                    encrypted = f.encrypt(dob_str.encode('utf-8')).decode('utf-8')
                    cursor.execute(
                        "UPDATE accounts_userprofile SET date_of_birth = %s WHERE id = %s",
                        [encrypted, row_id],
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_social_auth_provider_and_avatar'),
    ]

    operations = [
        # Step 1: Encrypt existing plain text data in-place
        migrations.RunPython(encrypt_existing_data, migrations.RunPython.noop),

        # Step 2: Update Django's schema state (no DB column type change — VARCHAR stays VARCHAR)
        migrations.AlterField(
            model_name='socialauthprovider',
            name='client_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialauthprovider',
            name='client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_requirements',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_whatsapp',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
