# Generated by Django 6.0.2 on 2026-02-27 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='geo-alt', max_length=50)),
                ('colour', models.CharField(default='#F97316', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourCodeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=200)),
                ('location_lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('capacity', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('min_fitness_level', models.PositiveSmallIntegerField(default=1)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rsvp_deadline_hours', models.PositiveSmallIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MapRouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('WALKING', 'Walking'), ('DRIVING', 'Driving')], default='WALKING', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='tours.tour')),
            ],
            options={
                'ordering': ['route_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], default='EASY', max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.activitycategory')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='tours.tour')),
            ],
            options={
                'ordering': ['day', 'order', 'start_time'],
            },
        ),
    ]
