# Generated by Django 6.0.2 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
