# Generated by Django 6.0.2 on 2026-02-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_itineraryitem_options_tour_tour_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='tours.activitycategory'),
        ),
    ]
