# Generated by Django 6.0.2 on 2026-02-28 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_itineraryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='colour',
            field=models.CharField(default='#F97316', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Must be a valid hex colour, e.g. #F97316')]),
        ),
    ]
