# Generated by Django 6.0.2 on 2026-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_whatsapp_sos', models.BooleanField(default=True)),
                ('show_sa_emergency_numbers', models.BooleanField(default=True)),
                ('show_gps_share', models.BooleanField(default=True)),
                ('show_first_aid', models.BooleanField(default=True)),
                ('show_emergency_contacts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SOS Configuration',
            },
        ),
    ]
